---
- name: Sync all PAH DE and Remote Repos
  hosts: localhost
  gather_facts: false
  become: false
  tags: sync

  roles:
    - sync_de
    - sync_repos

- name: Build new Shadowmande
  hosts: ansibledev.shadowman.dev
  tags: buildde

  roles:
    - build_shadowmande
