---
ee_version: 3
dest_dir: /home/ansible/ansible/builder/shadowmaneedev/
pah_name: tower.shadowman.dev
image_name: shadowmaneedev
bindep_file: bindep.txt
python_requirements_file: requirements.txt
galaxy_requirements_file: requirements.yml
ee_base_image: tower.shadowman.dev/ansible-automation-platform/ee-minimal-rhel8:2.16
ee_base_sig_name: registry.redhat.io/ansible-automation-platform/ee-minimal-rhel8:2.16
galaxy_keyring: /home/ansible/ansible/builder/shadowmanee/fullkeyring.kbx
ee_package_manager_path: /usr/bin/microdnf
ee_build_files:
  - src: /home/ansible/ansible/builder/shadowmaneedev/ansible.cfg
    dest: configs
  - src: /home/ansible/ansible/builder/shadowmaneedev/.bashrc
    dest: configs
  - src: /home/ansible/ansible/builder/shadowmaneedev/shells
    dest: configs
ee_bindep:
  - python3-jinja2 [platform:rpm]
  - which [platform:rpm]
  - git [platform:rpm]
  - libcurl-devel [platform:rpm]
  - gcc [platform:rpm]
  - python39-devel [platform:rpm]
  - openssl-devel [platform:rpm]
  - libxml2-devel [platform:rpm]
  - libxslt-devel [platform:rpm]
ee_python:
  - scp
  - pyats
  - genie
  - python-jenkins
  - pan-os-python==1.8.0
  - pan-python==0.17.0
  - panos-upgrade-assurance==0.3.0
ee_collections:
  - name: amazon.aws
  - name: ansible.controller
  - name: ansible.eda
  - name: ansible.hub
  - name: ansible.netcommon
  - name: ansible.posix
  - name: ansible.platform
  - name: ansible.utils
  - name: ansible.windows
  - name: arista.eos
  - name: azure.azcollection
  - name: cisco.ios
  - name: cloud.terraform
  - name: community.postgresql
  - name: community.crypto
  - name: community.general
  - name: community.vmware
  - name: community.windows
  - name: containers.podman
  - name: datadog.dd
  - name: dynatrace.oneagent
  - name: f5networks.f5_modules
  - name: ibm.qradar
  - name: infra.aap_configuration
  - name: microsoft.ad
  - name: netscaler.adc
  - name: paloaltonetworks.panos
  - name: redhat.insights
  - name: redhat.openshift
  - name: redhat.rhv
  - name: redhat.satellite
  - name: servicenow.itsm
  - name: shadowman.reports
  - name: vmware.vmware_rest
    version: 1.0.1
  - name: vyos.vyos
ee_prepend_galaxy:
  - ADD _build/configs/ansible.cfg /etc/ansible/ansible.cfg
ee_prepend_builder:
  - ENV PKGMGR_OPTS "--nodocs --setopt install_weak_deps=0 --enablerepo=rhocp-4.13-for-rhel-8-x86_64-rpms"
ee_prepend_final:
  - ENV PKGMGR_OPTS "--nodocs --setopt install_weak_deps=0 --enablerepo=rhocp-4.13-for-rhel-8-x86_64-rpms"
ee_append_final:
  - RUN microdnf install -y yum-utils
  - RUN dnf config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
  - RUN dnf install -y terraform
  - RUN microdnf reinstall tzdata -y
  - RUN git clone -b citrix.adc --single-branch https://github.com/netscaler/ansible-collection-netscaleradc.git /tmp/citrix
  - RUN pip3 install /tmp/citrix/deps/nitro-python-1.0_kamet.tar.gz
  - RUN rm -rf /tmp/citrix/
  - RUN rm -f /etc/ansible/ansible.cfg
  - RUN /usr/bin/microdnf install python3.11 python3.11-pip -y
  - RUN /usr/bin/python3.11 -m pip install --no-cache-dir ansible-dev-tools
  - RUN microdnf clean all
  - RUN dnf clean all
# Provide shell and bash set up for the workspace
  - COPY _build/configs/shells /etc/shells
  - COPY _build/configs/.bashrc /home/runner/.bashrc
  - RUN printf "export CONTAINER_NAME=ansibleee\n" >> /home/runner/.bashrc
# In OpenShift, container will run as a random uid number and gid 0. Make sure things
# are writeable by the root group.
  - RUN chgrp -R 0 /home && chmod -R g=u /etc/passwd /etc/group /home
