---
- name: Sync Remote EE using AH Configuration collection
  infra.ah_configuration.ah_ee_repository_sync:
    name: "{{ ee_image }}"
    wait: true
    timeout: 300
    ah_username: "{{ pah_user }}"
    ah_password: "{{ pah_pass }}"
    ah_host: "{{ lookup('env', 'AH_HOST') }}"
