---
ee_version: 3
dest_dir: /home/ansible/ansible/builder/venafiee/
pah_name: tower.shadowman.dev
image_name: venafiee
galaxy_requirements_file: requirements.yml
ee_base_image: tower.shadowman.dev/ansible-automation-platform/ee-minimal-rhel8:2.16
ee_base_sig_name: registry.redhat.io/ansible-automation-platform/ee-minimal-rhel8:2.16
galaxy_keyring: /certs/fullkeyring.kbx
ee_package_manager_path: /usr/bin/microdnf
ee_build_files:
  - src: /home/ansible/ansible/builder/venafiee/ansible.cfg
    dest: configs
ee_collections:
  - name: ansible.posix
  - name: ansible.windows
  - name: community.windows
  - name: microsoft.iis
  - name: venafi.machine_identity
  - name: community.crypto
ee_prepend_galaxy:
  - ADD _build/configs/ansible.cfg /etc/ansible/ansible.cfg
ee_append_final:
  - RUN rm -f /etc/ansible/ansible.cfg
  - RUN microdnf clean all
